name: mxliveoo
description: Premium Live TV Streaming App.
publish_to: 'none'
version: 1.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # UI & Network
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.3.0
  marquee: ^2.2.3
  url_launcher: ^6.2.6
  http: ^1.1.0
  
  # Video & System
  video_player: ^2.8.1
  chewie: ^1.7.1
  wakelock_plus: ^1.1.4
  floating: ^2.0.0      # New package for PiP mode

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
